config/routes.rb
Rails.application.routes.draw do
  root 'links#new'

  resources :links, only: %i[create new index]
  resources :statistics, only: :index

  get '/statistics/visits_from_countries/:link_id', to: 'statistics#show_countries', as: :statistics_visit_from_countries
  get '/statistics/visits_count/:link_id', to: 'statistics#show_count', as: :statistics_visit_count
  get '/:short_url', to: 'links#show', as: :link
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  FORMAT_LINK = /\A(https?:\/\/)?([\w-]{1,32}\.[\w-]{1,32})[^\s@]*/

  scope :sort_by_date, -> { order(created_at: :desc) }

  has_many :visits, dependent: :destroy

  validates_format_of :source_link, with: FORMAT_LINK
  validates :short_url, uniqueness: true
end
 

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include Links
  include Visits

  before_action :find_link, only: :show

  def index
    @links = Link.all.paginate(page: params[:page], per_page: 10).sort_by_date
  end

  def show
    create_visit(request.remote_ip, @link)
    redirect_to @link.source_link
  end

  def new
    @link = Link.new
  end

  def create
    if link_exist?(permitted_params[:source_link])
      @link = search_link(permitted_params[:source_link])
      respond_to { |format| format.js }
    else
      @link = Link.create(links_params)
      respond_to { |format| format.js }
    end
  end

  private

  def short_url
    encode(permitted_params[:source_link])
  end

  def find_link
    @link = Link.find_by(short_url: params[:short_url])
  end

  def permitted_params
    params.require(:link).permit(:source_link)
  end

  def links_params
    { source_link: permitted_params[:source_link], short_url: short_url }
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :find_link, only: %i[show_count show_countries]

  def index
    render json: { 'All redirections' => Visit.count }
  end

  def show_count
    render json: { 'Unique redirections' => @link.visits.count  }
  end

  def show_countries
    render json: @link.visits.group(:country).count
  end

  private

  def find_link
    @link = Link.find(params[:link_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def short_url(short)
    ENV['APP_HOST'] + short
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortenerUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_create.html.erb
<%= link_to short_url(@link.short_url), link_path(@link.short_url), target: '_blank'%>
<hr>

app/views/links/_errors.html.erb
<div class="errors">
  <h2><%= pluralize(@link.errors.count, 'error')%> detected:</h2>

  <ul>
    <% @link.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/links/create.js.erb
$("#link_errors").empty();
$('#new-link')[0].reset();

<% if @link.errors.present? %>
  $("#short_link").empty();
  $("<%= escape_javascript(render 'errors') %>").appendTo("#link_errors");
<% else %>
  $("<%= escape_javascript(render 'create') %>").prependTo("#short_link");
<% end %>

app/views/links/index.html.erb
<div class="all_redirections">
  <h2 class="all-links">All redirections</h2>
  <%= bar_chart statistics_path %>
</div>

<h3 class="all-links">All links</h3>

<ul class="list-group">
  <% @links.each do |link| %>
    <li class="list-group-item">
      <%= link_to short_url(link.short_url), link_path(link.short_url), target: '_blank' %>
      <%= bar_chart statistics_visit_count_path(link.id) %>
      <%= pie_chart statistics_visit_from_countries_path(link.id), messages: { empty: "No redirections" } %>
    </li>
  <% end %>
  <%= will_paginate @links %>
</ul>

app/views/links/new.html.erb
<h1 class="header">Enter your link</h1>

<div id='link_errors'>
</div>


<%= form_with model: @link, id: 'new-link' do |form| %>
  <div class="input-group mb-3">
    <%= form.text_field :source_link, class: 'form-control' %>
    <div class="input-group-append">
      <%= submit_tag 'Create link', class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

<div id="short_link">
</div>

app/views/shared/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 black-bg border-bottom shadow-sm">

  <h5 class="my-0 mr-md-auto font-weight-normal">
    <%= link_to 'Url Shortener', root_path, class: 'text-white' %>
  </h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to 'all links', links_path, class: "p-2 text-white" %>
  </nav>
</div>